spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: localhost  # Redis server host
      port: 6379       # Redis server port
      password: mypassword  # Redis password, if set


custom:
  jwt:
    #hardcoded 256-bit hex formatted secret key
    #generated on https://allkeysgenerator.com/random/security-encryption-key-generator.aspx
    secret: 77397A24432646294A404E635266556A586E3272357538782F4125442A472D4B
    expiration: 7200000