spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

